---

- name: Start Client
  k8s:
    definition: "{{ lookup('template', 'client.yml.j2') | from_yaml }}"

- name: Wait for pod to be running...
  k8s_facts:
    kind: Pod
    api_version: v1
    namespace: "{{ operator_namespace }}"
    label_selectors:
      - app = hammerdb-client
    register: client_pods
    