apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
  name: hammerdb-benchmark
  namespace: my-ripsaw
spec:
  workload:
    name: hammerdb
    args:
      db_server: false
      db_port: false
      warehouses: 1
      workers: 1
      protocol: "tcp"
      runtime: 30
      